flatcar/flatcar-website

content/faq.md
closes #243
updated dead link in [https://www.flatcar.org/faq](https://www.flatcar.org/faq) pointing to [https://kinvolk.io/docs/flatcar-container-linux](https://kinvolk.io/docs/flatcar-container-linux) to point to [https://flatcar-linux.org/docs/latest/](https://flatcar-linux.org/docs/latest/)
Click on the link and it leads you to Flatcar's docs :)
Manually tested and  the new link works.
=> update dead link to flatcar documentation

themes/flatcar/layouts/docs/redirect.html
The meta tag prepends /docs/ to the link, but this prefix is missing on the HTML link.
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
When clicking on the *Docs* link on Flatcar main web page and that your browser is configured not to follow redirections by default, it shows a page with the text `Please follow [this link](latest).` on `https://www.flatcar.org/docs`.
If you click on the link, you arrive to `https://www.flatcar.org/latest` which is a 404 error page, instead of …
=> themes/flatcar/layouts: Fix HTML link on docs redirection page

content/_index.md
The Kinvolk Update Service was the hosted offering of Nebraska. Just refer to Nebraska as software component because this section talks about Flatcar's architecture.
=> index: Refer to Nebraska for the update service

content/docs/latest/installing/_index.md, content/docs/latest/installing/vms/libvirt.md, content/docs/latest/installing/vms/qemu.md, content/docs/latest/tutorial/hands-on-1/_index.md, content/docs/latest/tutorial/hands-on-2/_index.md, content/docs/latest/tutorial/hands-on-4/_index.md
We now provide the qcow2 image with inline compression. This means we can skip the unpacking. This is available from Stable 3602.2.0 and the hands-on 4 tutorial was updated to this version - it will update to 3602.2.1.
Reopened from https://github.com/flatcar/flatcar-docs/pull/340
=> Skip the unpacking of the QEMU image

content/docs/latest/container-runtimes/getting-started-with-kubernetes.md
We use GitHub release assets to host the config files and images. To have a stable reference we now only accumulate everything in the "latest" release.
=> k8s: Use new permanent URL for sysext-bakery release assets

data/releases/beta/3760.1.0.yml, data/releases/beta/current.yml, data/releases/stable/3602.2.2.yml, data/releases/stable/current.yml
This small change replaces the `:warning:` semantic emoji - which does not render in Hugo and hence appears as a literal `:warning:` string - with the UTF8 emoji ⚠️.
=> data/releases/stable, beta: fix torcx removal warning

update-flatcar-versions.sh
- update-flatcar-versions: Make script more robust
There were many warnings in
shellcheck -o all -e SC2292 -e SC2250
Address them and add additional checks for the active LTS fetching.
- update-flatcar-versions: Allow passing a custom branch
`./update-flatcar-versions.sh` # with export GH_* before
=> update-flatcar-versions: Allow passing a custom branch

content/blog/2023-12-18-torcx-deprecation-for-systemd-sysext.md
A blog post on our move from torcx to systemd-sysext.
=> content/blog: torcx deprecation in favour of sysext

content/docs/latest/installing/cloud/azure.md
The passing of Ignition as custom data is different from the newer user data mechanism. Custom data relies on CD-ROM emulation while user data relies on a regular cloud HTTP endpoint. Custom data is only available once on the first boot, while user data is available afterwards, too. Thus, both have their tradeoffs but since we now support user data in Flatcar and it is a bit more easy to use, it makes sense to recommend it.
Call out that user data is supported and switch the examples over to user data, while documenting custom data as alternative.
=> azure: Recommend user data over custom data for Ignition

.github/workflows/azure-static-web-apps-lemon-wave-085522403.yml
This is to avoid using deprecated node16.
=> .github: Bump github actions

content/docs/latest/reference/developer-guides/sdk-modifying-flatcar.md
`run_sdk_container.sh` renamed to `run_sdk_container` at some point or possibly a typo.
=> fixes broken run_sdk_container invocations in in developer-guides

config.yaml
The "edit this page" link is current broken. Fix it.
=> Fix edit page link after docs repo rename

content/docs/latest/container-runtimes/getting-started-with-kubernetes.md
In this PR we update Kubernetes tested versions.
To be merged after: https://github.com/flatcar/mantle/pull/503
=> kubernetes: update tested versions

content/docs/latest/installing/_index.md
adding the path to install QEMU  QEMU image and the helper script for ARM64 architecture
=> Updating the start guide

content/docs/latest/installing/cloud/azure.md
Documenting the problem with terraform's linux virtual machine and data disks
Referring to https://github.com/flatcar/Flatcar/issues/1297
=> azure: known issue data disk with terraform

content/docs/latest/setup/releases/update-strategies.md
Otherwise `motdgen` service can error with `command not found`.
To address https://github.com/coreos/bugs/issues/1902
=> Add quote for `LOCKSMITHD_REBOOT_WINDOW_START` value

content/docs/latest/_index.md, content/docs/latest/setup/security/luks.md
A long-requested feature is disk encryption. In the next Alpha we have everything in place for TPM-backed disk encryption with systemd-cryptenroll and Clevis, and with a network-backed disk secret store with Tang.
Document the limitations, implications and the Ignition configs.
Preview URL suffix: `/docs/latest/setup/security/luks/`
=> docs: Document TPM-backed rootfs encryption

content/docs/latest/setup/releases/update-strategies.md
This came up in GitHub issues and it's helpful to document workarounds.
=> update-strategies: Document workarounds for update problems

content/docs/latest/setup/storage/adding-swap.md
With the generator added in https://github.com/flatcar/scripts/pull/1772 we don't need the manual setup anymore.
Creating the config file worked, as also tested in the linked PR.
I think we could even add this config by default to prevent hitting out-of-memory errors with Kubernetes on small VM sizes.
=> docs: Document new zram generator

content/docs/latest/_index.md, content/docs/latest/installing/vms/hyper-v.md
Add the Hyper-V VM documentation:
* how to create a VM
* how to provision a VM via config drive or Ignition
* example of a more advanced TPM LUKS2 encryption scenario, with autologin and password set
See: https://github.com/flatcar/Flatcar/issues/1009
=> docs: hyper-v: added documentation for using Flatcar with Hyper-V

content/docs/latest/_index.md, content/docs/latest/provisioning/sysext/_index.md, content/docs/latest/setup/storage/zfs.md
The use of systemd-sysext for OEM and Flatcar extensions was only documented in the release notes but not yet part of the docs. Add an overview about the systemd-sysext use in Flatcar and remove the Butane sysupdate config because the sysext-bakery is the better place to keep this up-to-date.
@jepio wanted to document the ZFS extension and I think it would make sense to cover the ZFS specifics with examples under https://www.flatcar.org/docs/latest/setup/storage/
Improvements and additions to the topic of Flatcar extension in general are welcome and would go into this PR, while we can make a new PR for ZFS examples in the storage docs pages.
=> sysext: Document OEM extensions and Flatcar extensions

content/docs/latest/provisioning/sysext/_index.md
Follow up for https://github.com/flatcar/flatcar-website/pull/319
As discussed in https://github.com/flatcar/Flatcar/issues/1409 the page on systemd-sysext images should also cover the customization of release images by putting extensions into the rootfs. Instead of having duplicate content that we need to keep up to date, add a reference to the systext-bakery README.
=> docs: Document bake_flatcar_image.sh script

content/docs/latest/container-runtimes/getting-started-with-kubernetes.md
When the condition fails we don't want to propagate this to the unit. Sync this with the files from CAPO which also prevents major updates.
=> docs: Fix Kubernetes systemd-sysext post update action

content/docs/latest/_index.md, content/docs/latest/installing/vms/kubevirt.md
Added how to on downloading the KubeVirt oem image and how to create a KubeVirt VM with userdata in both supported formats:
* ConfigDrive
* Ignition
=> docs: kubevirt: add documentation

content/docs/latest/reference/developer-guides/sdk-tips-and-tricks.md
Docs changes relating to flatcar/scripts#2047.
=> Update package maintenance guide for the git-r3 eclass

content/docs/latest/reference/developer-guides/sdk-bootstrapping.md
Documentation changes associated with flatcar/scripts#2115.
=> Revise SDK bootstrap process according to new seed update procedure

content/docs/latest/nebraska/i18n/_index.md
only changed the word "Headlamp" to "Nebraska"
=> fix mention of "Headlamp" to "Nebraska

content/docs/latest/nebraska/development.md
Remove text and link to contributing document, as those are already included in the development document.
Fixes https://github.com/flatcar/nebraska/issues/849
=> Remove text and link to contributing document

content/docs/latest/reference/developer-guides/kernel-modules.md
The devcontainer docs were using `/usr/lib64/modules` instead of `/usr/lib/modules`. However, the former is a symlink to the latter, leading to the mount unit failing. The symlink was introduced by release 3200.0.0.
Also, systemd-nspawn required `--capability=CAP_NET_ADMIN` in order to prevent "loopback permission denied" error messages.
=> kernel-modules: update devcontainer docs

content/docs/latest/setup/systemd/user-units.md
This helps with both unit files and podman quadlets that run rootless containers.
flatcar/Flatcar#1666
Documentation for systemd user units and podman quadlets that helps run rootless containers.  This is focused on adding these during provisioning and ensuring that the network is started.
documentation
I tested the docs
=> Add documentation for systemd unit files

content/docs/latest/installing/cloud/openstack.md
as described in documents we need to transform yaml -> json format and use json as user-data on openstack
=> fix: ignition.json uses as user-data instead of ignition.ign

content/docs/latest/installing/cloud/openstack.md
Follow-up to https://github.com/flatcar/flatcar-website/pull/377, fixed another occurrence of the same typo.
=> docs / openstack.md - fix `config.ign` => `ignition.json`

content/docs/latest/reference/developer-guides/sdk-modifying-flatcar.md
I added documentation about testing custom Flatcar modifications using the kola testing framework. This includes both (1) automated and (2) manual testing approaches to help developers validate their changes effectively.
Should close [[RFE] Add documentation on running the test suite locally](https://github.com/flatcar/Flatcar/issues/1189)
=> docs: add comprehensive documentation about testing custom Flatcar modifications

content/docs/latest/reference/developer-guides/sdk-modifying-flatcar.md
Dracut is no longer run in a chroot, so bootengine.cpio is created alongside the other build files rather than in the board root and is therefore no longer persisted.
To be honest, there was probably no need to delete it anyway, as it would have been overwritten. It seems like this was just a precaution.
sys-kernel/bootengine may end up being installed to the SDK rather than the board root, but that hasn't happened yet.
=> docs: No need to manually delete bootengine.cpio any more

content/docs/latest/reference/developer-guides/sdk-modifying-flatcar.md
This pull request updates the developer guide for modifying Flatcar SDK to include instructions for handling forks of the `scripts` repository. 
Documentation update:
* [`content/docs/latest/reference/developer-guides/sdk-modifying-flatcar.md`](diffhunk://#diff-946c90973717524d17507a5d2d27b99c78ef7670d9d0dce8ccdca77e4ba61033R79-R85): Added a note and steps to fetch tags from the upstream repository when working with a fork of the `scripts` repository. This prevents build errors during SDK container setup caused by missing tags.
Fixes: https://github.com/flatcar/Flatcar/issues/1705
=> docs: Add instructions for fetching tags when using a fork of the scripts repository

content/docs/latest/provisioning/sysext/_index.md, content/docs/latest/setup/customization/using-nvidia.md
This documents differences between the original nvidia.service and prebuilt sysext. It also provides basic example of Butane config.
=> using-nvidia: initial documentation

content/docs/latest/installing/bare-metal/booting-with-pxe.md, content/docs/latest/installing/cloud/aws-ec2.md, content/docs/latest/installing/vms/libvirt.md, content/docs/latest/installing/vms/qemu.md, content/docs/latest/installing/vms/vagrant.md
IRC channel is mostly deprecated, and not used. The recommended platform is Matrix/Element now.
=> docs: Change IRC references to Matrix

.github/workflows/flatcar-releases-pr.yml
I cannot test the real one without a dummy workflow having already been run once. I tried to test it in a fork, but it lacked the permissions to access the private flatcar-linux-release-info repo.
=> ci(github-actions): Create dummy releases PR workflow ahead of real one

CODEOWNERS
This PR updates the CODEOWNERS file to assign the appropriate specialized maintainer team (@flatcar/flatcar-communication) for pull request reviews, addressing the manual reviewer assignment issues outlined in https://github.com/flatcar/Flatcar/issues/1791.
This ensures that reviews are directed to team members with the most relevant domain expertise.
=> Update CODEOWNERS with specialized team assignment
